_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
num_rounds:
    value: 5
strategy:
    value: FedAvg
